name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jclugo/app-ejemplo:latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run unit tests and save results
        run: |
          pytest test-sumar.py > result.log || true
          pytest test-restar.py >> result.log || true
          pytest test-multiplicar.py >> result.log || true
          cat result.log

      - name: Show test summary metrics
        run: |
          PASSED_COUNT=$(grep -o 'PASSED' result.log | wc -l)
          FAILED_COUNT=$(grep -o 'FAILED' result.log | wc -l)
          echo "✅ Tests passed: $PASSED_COUNT"
          echo "❌ Tests failed: $FAILED_COUNT"